name: ar6-aerosol-uncertainty
channels:
  - chrisroadmap
  - conda-forge
  - defaults
dependencies:
  - climateforcing
  - jupyter
  - nbstripout
  - fair
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - seaborn
  - scipy
  - tqdm
  - xarray
# if you need to pip install anything:
#   - pip
#   - pip:
#     - thing-to-pip-install
